FROM zjuchenyuan/base

RUN git clone https://github.com/mozilla/gecko-dev --depth 1

# Credit: https://github.com/google/oss-fuzz/blob/master/projects/spidermonkey/build.sh

ENV SHELL=/bin/bash
RUN apt update && cd /gecko-dev && ./mach bootstrap --no-interactive --application-choice browser

ADD firefox_65dc081_20200131.patch /gecko-dev/
ADD mozbuild.patch /gecko-dev/
RUN cd /gecko-dev && patch -p1 < firefox_65dc081_20200131.patch && patch -p1 < mozbuild.patch &&\
    cd /gecko-dev/js/src && wget https://github.com/googleprojectzero/fuzzilli/raw/master/Targets/Spidermonkey/fuzzbuild.sh && bash fuzzbuild.sh

RUN curl https://swift.org/builds/swift-5.1.4-release/ubuntu1604/swift-5.1.4-RELEASE/swift-5.1.4-RELEASE-ubuntu16.04.tar.gz | tar xzf - --strip-components 1
RUN git clone https://github.com/googleprojectzero/fuzzilli &&\
    cd /fuzzilli && swift build